// Copyright 2015 Palantir Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package com.palantir.gradle.versions.flexversioning

/**
 * A POJO holding the version information for a commit in a repository. The full version string is generated by
 * {@link FlexVersion#getFullVersion}, and the individual components can be accessed through the public fields.
 */
class FlexVersion {
    public String domain = null
    public int commitCount = -1
    public String gitHash = null
    public boolean domainOnlyVersion = false
    public boolean dirty = false

    public FlexVersion(String domain, int commitCount, String gitHash, boolean domainOnlyVersion, boolean dirty) {
        this.domain = domain
        this.commitCount = commitCount
        this.gitHash = gitHash.take(12)
        this.domainOnlyVersion = domainOnlyVersion
        this.dirty = dirty
    }

    String getFullVersion() {
        def fullVersion
        if (domainOnlyVersion) {
            fullVersion = domain
        } else {
            fullVersion = "${domain}-${commitCount}-g${gitHash}"
        }

        if (dirty) {
            fullVersion = "${fullVersion}-dirty"
        }

        fullVersion
    }

    @Override
    public String toString() {
        return this.fullVersion
    }
}
